### ISSUE TITLE
Unable to stream spotify (

### ISSUE THREAD

**Issue by curiousercreative** [jaedb/Iris#1001]
### Iris version

3.70.0

### Operating system(s) affected

- [ ] Windows
- [ ] MacOS
- [ ] iOS
- [ ] Android
- [x] Linux
- [ ] Other

### Browser(s) affected

- [ ] Firefox
- [ ] Chrome
- [ ] Edge
- [ ] Other

### What happened?

When attempting to play a spotify track, Iris never starts playing and no error is displayed. Checking mopidy logs you find an error. Seems to be related to this thread https://discourse.mopidy.com/t/mopidy-stopped-playing-spotify/6151

### Logs

```shell
mopidy-1  | ERROR    2025-08-20 15:48:54,595 [7:MainThread] mopidy.audio.gst
mopidy-1  |   GStreamer error: Resource not found.
```

**Comment by curiousercreative** [comment]
> Spotify not steaming is unlikely to be a problem with a frontend client like Iris. Did you try another client? Have you rebuilt your gst Spotify plugin lately to use the latest dev version of librespot that has the latest fixes?

I should have mentioned this is an issue of the iris docker image with includes mopidy and optionally installs plugins like mopidy-spotify. I tried manually installing your left gst from the thread I linked to, but there must be more needed as I get the same result.

**Comment by jaedb** [comment]
There are some recent issues with librespot playback (due to changes on the Spotify end), but there isn't a new version released for [Alpine](https://pkgs.alpinelinux.org/package/edge/testing/x86/librespot) containing recent fixes yet. Please feel free to poke the librespot team for a published build!

See
* https://github.com/librespot-org/librespot/issues/1527
* https://github.com/librespot-org/librespot/issues/1521

**Comment by roderickvd** [comment]
We released v0.7.0 today.

**Comment by roderickvd** [comment]
No, I don’t know.

**Comment by curiousercreative** [comment]
@jaedb with latest packages, I still had to manually build and install per [instructions here](https://github.com/kingosticks/gst-plugins-rs-build) in my iris docker container. Only now are spotify tracks playable.

**Comment by Hurlu** [comment]
Hi @curiousercreative , would you mind sharing which specific tag of [gst-plugins-rs](https://github.com/kingosticks/gst-plugins-rs) did you end up going with ?

I tried myself re-building the [Dockerfile](https://github.com/jaedb/Iris/blob/master/Dockerfile) (non-Alpine, as it seems to be the default in docker hub) with gst-plugin-spotify_0.15.0-alpha.1-4 (still the same GStreamer issue, also lost search function) and gst-plugin-spotify_0.15.0-alpha.1-3 , same issues :/

All I did was add `--branch=gst-plugin-spotify_0.15.0-alpha.1-4` in the Dockerfile where the gst-plugins-rs repo gets cloned, is there anything else you did on your end ?
