### ISSUE TITLE
"Playlists" leads to a blank page

### ISSUE THREAD

**Issue by LiranSX** [jaedb/Iris#650]
environment - using iris version 3.54.1 on raspberry pi 3 (raspbian buster with latest updates), the issue reproduces on firefox 82.03, and chrome 86.0.4240.183 from windows - also from my galaxy S20 phone with latest chrome:
* click on "Playlists" -> you get a blank page (i have ~20 playlists, not using any external service like spotify etc.)
cleared browser cache and retried in all of them - still reproducible.
by enabling debug mode and clicking "playlists" - this is the console output:

LibraryPlaylists.js:360 Uncaught TypeError: Cannot read property 'id' of null
    at Function.mapStateToProps [as mapToProps] (LibraryPlaylists.js:360)
    at mapToPropsProxy (wrapMapToProps.js:41)
    at Function.detectFactoryAndVerify (wrapMapToProps.js:50)
    at mapToPropsProxy (wrapMapToProps.js:41)
    at handleFirstCall (selectorFactory.js:22)
    at pureFinalPropsSelector (selectorFactory.js:63)
    at connectAdvanced.js:319
    at mountMemo (react-dom.development.js:15442)
    at Object.useMemo (react-dom.development.js:15738)
    at useMemo (react.development.js:1521)
    at ConnectFunction (connectAdvanced.js:304)
    at renderWithHooks (react-dom.development.js:14803)
    at updateFunctionComponent (react-dom.development.js:17034)
    at updateSimpleMemoComponent (react-dom.development.js:16972)
    at updateMemoComponent (react-dom.development.js:16861)
    at beginWork (react-dom.development.js:18682)
    at HTMLUnknownElement.callCallback (react-dom.development.js:188)
    at HTMLUnknownElement.sentryWrapped (helpers.js:71)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:237)
    at invokeGuardedCallback (react-dom.development.js:292)
    at beginWork$1 (react-dom.development.js:23203)
    at performUnitOfWork (react-dom.development.js:22157)
    at workLoopSync (react-dom.development.js:22130)
    at performSyncWorkOnRoot (react-dom.development.js:21756)
    at react-dom.development.js:11089
    at unstable_runWithPriority (scheduler.development.js:653)
    at runWithPriority$1 (react-dom.development.js:11039)
    at flushSyncCallbackQueueImpl (react-dom.development.js:11084)
    at flushSyncCallbackQueue (react-dom.development.js:11072)
    at discreteUpdates$1 (react-dom.development.js:21893)
    at discreteUpdates (react-dom.development.js:806)
    at dispatchDiscreteEvent (react-dom.development.js:4168)
    at HTMLDocument.sentryWrapped (helpers.js:71)
mapStateToProps @ LibraryPlaylists.js:360
mapToPropsProxy @ wrapMapToProps.js:41
detectFactoryAndVerify @ wrapMapToProps.js:50
mapToPropsProxy @ wrapMapToProps.js:41
handleFirstCall @ selectorFactory.js:22
pureFinalPropsSelector @ selectorFactory.js:63
(anonymous) @ connectAdvanced.js:319
mountMemo @ react-dom.development.js:15442
useMemo @ react-dom.development.js:15738
useMemo @ react.development.js:1521
ConnectFunction @ connectAdvanced.js:304
renderWithHooks @ react-dom.development.js:14803
updateFunctionComponent @ react-dom.development.js:17034
updateSimpleMemoComponent @ react-dom.development.js:16972
updateMemoComponent @ react-dom.development.js:16861
beginWork @ react-dom.development.js:18682
callCallback @ react-dom.development.js:188
sentryWrapped @ helpers.js:71
invokeGuardedCallbackDev @ react-dom.development.js:237
invokeGuardedCallback @ react-dom.development.js:292
beginWork$1 @ react-dom.development.js:23203
performUnitOfWork @ react-dom.development.js:22157
workLoopSync @ react-dom.development.js:22130
performSyncWorkOnRoot @ react-dom.development.js:21756
(anonymous) @ react-dom.development.js:11089
unstable_runWithPriority @ scheduler.development.js:653
runWithPriority$1 @ react-dom.development.js:11039
flushSyncCallbackQueueImpl @ react-dom.development.js:11084
flushSyncCallbackQueue @ react-dom.development.js:11072
discreteUpdates$1 @ react-dom.development.js:21893
discreteUpdates @ react-dom.development.js:806
dispatchDiscreteEvent @ react-dom.development.js:4168
sentryWrapped @ helpers.js:71
Show 3 more frames
instrument.js:110 The above error occurred in the <ConnectFunction> component:
    in ConnectFunction (created by Context.Consumer)
    in Route (created by App)
    in Switch (created by App)
    in main (created by App)
    in div (created by App)
    in Route (created by App)
    in Switch (created by App)
    in div (created by App)
    in div (created by App)
    in App (created by ConnectFunction)
    in ConnectFunction (created by Context.Consumer)
    in Route
    in Router (created by BrowserRouter)
    in BrowserRouter
    in PersistGate
    in Provider

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://fb.me/react-error-boundaries to learn more about error boundaries.
(anonymous) @ instrument.js:110
logCapturedError @ react-dom.development.js:19527
logError @ react-dom.development.js:19564
update.callback @ react-dom.development.js:20708
callCallback @ react-dom.development.js:12490
commitUpdateQueue @ react-dom.development.js:12511
commitLifeCycles @ react-dom.development.js:19883
commitLayoutEffects @ react-dom.development.js:22803
callCallback @ react-dom.development.js:188
sentryWrapped @ helpers.js:71
invokeGuardedCallbackDev @ react-dom.development.js:237
invokeGuardedCallback @ react-dom.development.js:292
commitRootImpl @ react-dom.development.js:22541
unstable_runWithPriority @ scheduler.development.js:653
runWithPriority$1 @ react-dom.development.js:11039
commitRoot @ react-dom.development.js:22381
finishSyncRender @ react-dom.development.js:21807
performSyncWorkOnRoot @ react-dom.development.js:21793
(anonymous) @ react-dom.development.js:11089
unstable_runWithPriority @ scheduler.development.js:653
runWithPriority$1 @ react-dom.development.js:11039
flushSyncCallbackQueueImpl @ react-dom.development.js:11084
flushSyncCallbackQueue @ react-dom.development.js:11072
discreteUpdates$1 @ react-dom.development.js:21893
discreteUpdates @ react-dom.development.js:806
dispatchDiscreteEvent @ react-dom.development.js:4168
sentryWrapped @ helpers.js:71
LibraryPlaylists.js:360 Uncaught TypeError: Cannot read property 'id' of null
    at Function.mapStateToProps [as mapToProps] (LibraryPlaylists.js:360)
    at mapToPropsProxy (wrapMapToProps.js:41)
    at Function.detectFactoryAndVerify (wrapMapToProps.js:50)
    at mapToPropsProxy (wrapMapToProps.js:41)
    at handleFirstCall (selectorFactory.js:22)
    at pureFinalPropsSelector (selectorFactory.js:63)
    at connectAdvanced.js:319
    at mountMemo (react-dom.development.js:15442)
    at Object.useMemo (react-dom.development.js:15738)
    at useMemo (react.development.js:1521)
    at ConnectFunction (connectAdvanced.js:304)
    at renderWithHooks (react-dom.development.js:14803)
    at updateFunctionComponent (react-dom.development.js:17034)
    at updateSimpleMemoComponent (react-dom.development.js:16972)
    at updateMemoComponent (react-dom.development.js:16861)
    at beginWork (react-dom.development.js:18682)
    at HTMLUnknownElement.callCallback (react-dom.development.js:188)
    at HTMLUnknownElement.sentryWrapped (helpers.js:71)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:237)
    at invokeGuardedCallback (react-dom.development.js:292)
    at beginWork$1 (react-dom.development.js:23203)
    at performUnitOfWork (react-dom.development.js:22157)
    at workLoopSync (react-dom.development.js:22130)
    at performSyncWorkOnRoot (react-dom.development.js:21756)
    at react-dom.development.js:11089
    at unstable_runWithPriority (scheduler.development.js:653)
    at runWithPriority$1 (react-dom.development.js:11039)
    at flushSyncCallbackQueueImpl (react-dom.development.js:11084)
    at flushSyncCallbackQueue (react-dom.development.js:11072)
    at discreteUpdates$1 (react-dom.development.js:21893)
    at discreteUpdates (react-dom.development.js:806)
    at dispatchDiscreteEvent (react-dom.development.js:4168)
    at HTMLDocument.sentryWrapped (helpers.js:71)
mapStateToProps @ LibraryPlaylists.js:360
mapToPropsProxy @ wrapMapToProps.js:41
detectFactoryAndVerify @ wrapMapToProps.js:50
mapToPropsProxy @ wrapMapToProps.js:41
handleFirstCall @ selectorFactory.js:22
pureFinalPropsSelector @ selectorFactory.js:63
(anonymous) @ connectAdvanced.js:319
mountMemo @ react-dom.development.js:15442
useMemo @ react-dom.development.js:15738
useMemo @ react.development.js:1521
ConnectFunction @ connectAdvanced.js:304
renderWithHooks @ react-dom.development.js:14803
updateFunctionComponent @ react-dom.development.js:17034
updateSimpleMemoComponent @ react-dom.development.js:16972
updateMemoComponent @ react-dom.development.js:16861
beginWork @ react-dom.development.js:18682
callCallback @ react-dom.development.js:188
sentryWrapped @ helpers.js:71
invokeGuardedCallbackDev @ react-dom.development.js:237
invokeGuardedCallback @ react-dom.development.js:292
beginWork$1 @ react-dom.development.js:23203
performUnitOfWork @ react-dom.development.js:22157
workLoopSync @ react-dom.development.js:22130
performSyncWorkOnRoot @ react-dom.development.js:21756
(anonymous) @ react-dom.development.js:11089
unstable_runWithPriority @ scheduler.development.js:653
runWithPriority$1 @ react-dom.development.js:11039
flushSyncCallbackQueueImpl @ react-dom.development.js:11084
flushSyncCallbackQueue @ react-dom.development.js:11072
discreteUpdates$1 @ react-dom.development.js:21893
discreteUpdates @ react-dom.development.js:806
dispatchDiscreteEvent @ react-dom.development.js:4168
sentryWrapped @ helpers.js:71
Show 3 more frames
libflac.js:104 POST https://o99789.ingest.sentry.io/api/219026/store/?sentry_key=ca99fb6662fe40ae8ec4c18a466e4b4b&sentry_version=7 429 (Too Many Requests)
global.fetch @ libflac.js:104
(anonymous) @ instrument.js:136
(anonymous) @ fetch.js:46
SyncPromise @ syncpromise.js:73
./node_modules/@sentry/browser/esm/transports/fetch.js.FetchTransport.sendEvent @ fetch.js:44
./node_modules/@sentry/core/esm/basebackend.js.BaseBackend.sendEvent @ basebackend.js:38
./node_modules/@sentry/core/esm/baseclient.js.BaseClient._sendEvent @ baseclient.js:318
./node_modules/@sentry/browser/esm/client.js.BrowserClient._sendEvent @ client.js:46
(anonymous) @ baseclient.js:377
onfulfilled @ syncpromise.js:136
(anonymous) @ syncpromise.js:61
SyncPromise._executeHandlers @ syncpromise.js:55
SyncPromise._attachHandler @ syncpromise.js:46
(anonymous) @ syncpromise.js:126
SyncPromise @ syncpromise.js:73
./node_modules/@sentry/utils/esm/syncpromise.js.SyncPromise.then @ syncpromise.js:125
(anonymous) @ baseclient.js:348
SyncPromise @ syncpromise.js:73
./node_modules/@sentry/core/esm/baseclient.js.BaseClient._processEvent @ baseclient.js:346
./node_modules/@sentry/core/esm/baseclient.js.BaseClient.captureEvent @ baseclient.js:91
(anonymous) @ baseclient.js:65
onfulfilled @ syncpromise.js:136
(anonymous) @ syncpromise.js:61
SyncPromise._executeHandlers @ syncpromise.js:55
SyncPromise._attachHandler @ syncpromise.js:46
(anonymous) @ syncpromise.js:126
SyncPromise @ syncpromise.js:73
./node_modules/@sentry/utils/esm/syncpromise.js.SyncPromise.then @ syncpromise.js:125
./node_modules/@sentry/core/esm/baseclient.js.BaseClient.captureException @ baseclient.js:64
./node_modules/@sentry/hub/esm/hub.js.Hub._invokeClient @ hub.js:58
./node_modules/@sentry/hub/esm/hub.js.Hub.captureException @ hub.js:150
callOnHub @ index.js:16
captureException @ index.js:34
(anonymous) @ helpers.js:86
./node_modules/@sentry/hub/esm/hub.js.Hub.withScope @ hub.js:103
callOnHub @ index.js:16
withScope @ index.js:148
sentryWrapped @ helpers.js:76
invokeGuardedCallbackDev @ react-dom.development.js:237
invokeGuardedCallback @ react-dom.development.js:292
beginWork$1 @ react-dom.development.js:23203
performUnitOfWork @ react-dom.development.js:22157
workLoopSync @ react-dom.development.js:22130
performSyncWorkOnRoot @ react-dom.development.js:21756
(anonymous) @ react-dom.development.js:11089
unstable_runWithPriority @ scheduler.development.js:653
runWithPriority$1 @ react-dom.development.js:11039
flushSyncCallbackQueueImpl @ react-dom.development.js:11084
flushSyncCallbackQueue @ react-dom.development.js:11072
discreteUpdates$1 @ react-dom.development.js:21893
discreteUpdates @ react-dom.development.js:806
dispatchDiscreteEvent @ react-dom.development.js:4168
sentryWrapped @ helpers.js:71
Show 23 more frames

**Comment by jaedb** [comment]
Please update this issue to ensure it follows the provided issue template. Make sure to include the browser and version.

Also, it might be a silly question, but do you have any playlists? Have you authorized Spotify?

**Comment by atrizdawiz** [comment]
I have the same problem after upgrading. There are errors in the Chrome console:

`app.min.js?v=1605169008:116 Uncaught (in promise) TypeError: Cannot read property 'id' of null
    at Function.mapToProps (app.min.js?v=1605169008:116)
    at r (app.min.js?v=1605169008:1)
    at Function.r.mapToProps (app.min.js?v=1605169008:1)
    at r (app.min.js?v=1605169008:1)
    at app.min.js?v=1605169008:1
    at app.min.js?v=1605169008:1
    at Object.useMemo (app.min.js?v=1605169008:78)
    at t.useMemo (app.min.js?v=1605169008:70)
    at O (app.min.js?v=1605169008:1)
    at Ka (app.min.js?v=1605169008:78)
    at Mi (app.min.js?v=1605169008:78)
    at Di (app.min.js?v=1605169008:78)
    at Ri (app.min.js?v=1605169008:78)
    at yc (app.min.js?v=1605169008:78)
    at us (app.min.js?v=1605169008:78)
    at cs (app.min.js?v=1605169008:78)
    at $c (app.min.js?v=1605169008:78)
    at app.min.js?v=1605169008:78
    at t.unstable_runWithPriority (app.min.js?v=1605169008:86)
    at Yo (app.min.js?v=1605169008:78)
    at qo (app.min.js?v=1605169008:78)
    at Wo (app.min.js?v=1605169008:78)
    at Kc (app.min.js?v=1605169008:78)
    at Object.enqueueSetState (app.min.js?v=1605169008:78)
    at t.g.setState (app.min.js?v=1605169008:70)
    at app.min.js?v=1605169008:116
    at Object.y [as dispatch] (app.min.js?v=1605169008:1)
    at Object.Un [as rehydrate] (app.min.js?v=1605169008:116)
    at y (app.min.js?v=1605169008:116)
    at app.min.js?v=1605169008:116`

and a 500:
`VM89:1 POST https://o99789.ingest.sentry.io/api/219026/store/?sentry_key=ca99fb6662fe40ae8ec4c18a466e4b4b&sentry_version=7 429 (Too Many Requests)`

**Comment by ineentho** [comment]
Me and a couple of friends using the same server are having the same problem, both in Chrome and Firefox (currently having the issue on Firefox 83.0). It seems to be working in some cases, but I haven't figured out which case that is.

The same error is also logged on the search page, but only if the Spotify source is selected.

I haven't dug in depth, but the issue seem to be that [state].spotify.me is null for some reason.

If it is of any help, here's the full state at the time of the exception: https://gist.github.com/ineentho/58a87611487a3e980ee7dc5724b3a4f8

**Comment by jaedb** [comment]
@atrizdawiz and @LiranSX this is why the issue template is so important. Without it I have to spend hours of my personal, unpaid time to replicate the issue with no clear replication instructions, nor exact specs on the environmental variables (ie browser, OS, etc).

So, before I can investigate this any further, please complete the following:

---

**Describe the bug**
[A clear and concise description of what the bug is]

**To Reproduce**
Steps to reproduce the behavior:
1. Enable Test Mode (_Settings > Debug > Test Mode_). This provides more verbose error logs.
2. Go to '...'
3. Click on '....'
4. Scroll down to '....'
5. See error

**Expected behavior**
[A clear and concise description of what you expected to happen]

**Console log**
[Copy and paste your browser console log]

**Screenshots**
[If applicable, add screenshots to help explain your problem.]

**Environment details:**
 - OS: [e.g. iOS]
 - Browser [e.g. chrome, safari]
 - Iris version [e.g. 3.54.0]

**Additional context**
[Add any other context about the problem]

**Comment by ineentho** [comment]
I'm not able to reproduce the error any more after enabling the debug mode (nor after disabling it again :()

I forgot to include in my last comment that the relevant line of code seems to be in SPOTIFY_GET_SEARCH_RESUTLS: https://github.com/jaedb/Iris/blob/025b76d9228e24c52cafd0e48faf0e5082378b71/src/js/services/spotify/actions.js#L562

**Comment by jaedb** [comment]
Interesting. Enabling/disabling test mode will have a similar effect to clearing your browser cache (including the cached `iris.js`/`iris.min.js` app files). This may suggest that the issue is with an older version of Iris, despite you having the latest version running.

The `spotify.me.id` issue was resolved [last week](https://github.com/jaedb/Iris/commit/13c96665e96a9af051dc72c58365aa31c714621d) which would line up with the issue @ineentho and @atrizdawiz had described. I'm not sure whether it is the same as @LiranSX at this point though.

So the test now is to clear your browser cache, retry your steps and if the issue is gone, then it's a browser caching issue and the bug has already been fixed. Please confirm if this is the case.

**Comment by ineentho** [comment]
Interesting, that does seem like the case. I could've sworn that I did try to clear the cache, maybe it could be the service worker that hangs around even after clearing the cache?

I can't confirm that it is working because I can't even make spotify.me null again. Is there anything that I can do to make it null again, or does that only happen if something fails?

**Comment by ineentho** [comment]
I'm actually not positive your fix fixed the null issue, "repro":
```
(function() {
  'use strict'

    const getState = () => ({
        spotify: {
            me: null
        }
    })

    // This is what the code get transpiled to:
    var _getState = getState(),
        _getState$spotify$me = _getState.spotify.me;

    _getState$spotify$me = _getState$spotify$me === void 0 ? {} : _getState$spotify$me;
    var meId = _getState$spotify$me.id;
    
    // end transpiled code
    console.log(meId)
})()
```

The default value doesn't work for null:
```

(function() {
	const { a = 1} = {a: undefined} // Destructured a will be 1
	const { b = 1} = {b: null} // Destructured a will be null

  return {a, b}
})()
```

**Comment by LiranSX** [comment]
updated my initial bug report - tell me if there is anything else that can help.
BTW changing to "test mode" didn't solve the problem for me.

**Comment by atrizdawiz** [comment]
I have also updated my report.

**Comment by jaedb** [comment]
Thanks @LiranSX and @atrizdawiz. This helps confirm that @ineentho is on the right track, the destructuring code doesn't properly handle `null` (which is the default value when Mopidy-Spotify is not installed).

**Comment by ineentho** [comment]
Thanks a lot for the fix! I just wanted to add that I love the work you've done on Iris, it's by far the best third party Spotify frontend that I've ever come across (and that's of course ignoring that it's much more than that).

**Comment by LiranSX** [comment]
thanks - same here - though i'm using it only for playing local files/folders

**Comment by atrizdawiz** [comment]
Thank you, it worked after upgrading and clearing all site data from Chrome.
I like what you do, keep it up!

**Comment by jaedb** [comment]
Thanks team - it is great to see people enjoying the product of my hours of effort!

@LiranSX can you please clarify what you mean by the fix is not in release 3.54.2? Is your environment now working as expected, or is the issue persisting for you? Please remember to restart Mopidy and clear all your browser caches after upgrading.

**Comment by LiranSX** [comment]
it isn't fixed - cleared the cache and restarted several times since then - still same behavior. this is the log with test mode now:

react-dom.development.js:24994 Download the React DevTools for a better development experience: https://fb.me/react-devtools
autoMergeLevel1.js:35 redux-persist/stateReconciler: rehydrated keys 'mopidy, lastfm, genius, google, snapcast, _persist'
autoMergeLevel1.js:35 redux-persist/stateReconciler: rehydrated keys 'outputs, queue, queue_metadata, current_track, pinned, http_streaming_enabled, http_streaming_cachebuster, http_streaming_url, current_track_uri, seeds_resolved, radio, current_tracklist, next_track_uri, _persist'
autoMergeLevel1.js:35 redux-persist/stateReconciler: rehydrated keys 'language, theme, smooth_scrolling_enabled, hotkeys_enabled, playback_controls_touch_enabled, allow_reporting, wide_scrollbar_enabled, slim_mode, suppressed_broadcasts, grid_glow_enabled, window_title, uri_schemes_search_enabled, initial_setup_complete, _persist'
autoMergeLevel1.js:35 redux-persist/stateReconciler: rehydrated keys 'host, port, ssl, current_server, servers, mute, volume, play_state, uri_schemes, library_albums_uri, library_artists_uri, consume, random, repeat, _persist'
autoMergeLevel1.js:35 redux-persist/stateReconciler: rehydrated keys 'me, enabled, country, locale, _persist'
autoMergeLevel1.js:35 redux-persist/stateReconciler: rehydrated keys 'connected, username, client_id, version, config, connecting, commands, pinned, upgrading, connection_id, _persist'
loadGA.js:23 GET https://www.google-analytics.com/analytics.js net::ERR_NAME_NOT_RESOLVED
(anonymous) @ loadGA.js:23
(anonymous) @ loadGA.js:24
initialize @ core.js:143
App @ App.js:76
constructClassInstance @ react-dom.development.js:12880
updateClassComponent @ react-dom.development.js:17100
beginWork @ react-dom.development.js:18620
beginWork$1 @ react-dom.development.js:23179
performUnitOfWork @ react-dom.development.js:22157
workLoopSync @ react-dom.development.js:22130
performSyncWorkOnRoot @ react-dom.development.js:21756
(anonymous) @ react-dom.development.js:11089
unstable_runWithPriority @ scheduler.development.js:653
runWithPriority$1 @ react-dom.development.js:11039
flushSyncCallbackQueueImpl @ react-dom.development.js:11084
flushSyncCallbackQueue @ react-dom.development.js:11072
scheduleUpdateOnFiber @ react-dom.development.js:21199
enqueueSetState @ react-dom.development.js:12639
./node_modules/react/cjs/react.development.js.Component.setState @ react.development.js:471
(anonymous) @ react.js:61
dispatch @ redux.js:222
rehydrate @ persistStore.js:79
_rehydrate @ persistReducer.js:61
(anonymous) @ persistReducer.js:90
Promise.then (async)
(anonymous) @ persistReducer.js:89
Promise.then (async)
(anonymous) @ persistReducer.js:84
combination @ redux.js:459
(anonymous) @ persistReducer.js:99
dispatch @ redux.js:213
(anonymous) @ middleware.js:643
(anonymous) @ middleware.js:162
(anonymous) @ middleware.js:53
(anonymous) @ middleware.js:55
(anonymous) @ middleware.js:203
(anonymous) @ middleware.js:886
(anonymous) @ middleware.js:1948
(anonymous) @ middleware.js:238
(anonymous) @ middleware.js:765
(anonymous) @ index.js:11
persist @ persistStore.js:114
persistStore @ persistStore.js:123
./src/js/store/index.js @ index.js:266
__webpack_require__ @ bootstrap:19
./src/js/index.js @ index.js:2
__webpack_require__ @ bootstrap:19
0 @ app.scss?3f94:7
__webpack_require__ @ bootstrap:19
(anonymous) @ bootstrap:83
(anonymous) @ bootstrap:83
LibraryPlaylists.js:360 Uncaught TypeError: Cannot read property 'id' of null
    at Function.mapStateToProps [as mapToProps] (LibraryPlaylists.js:360)
    at mapToPropsProxy (wrapMapToProps.js:41)
    at Function.detectFactoryAndVerify (wrapMapToProps.js:50)
    at mapToPropsProxy (wrapMapToProps.js:41)
    at handleFirstCall (selectorFactory.js:22)
    at pureFinalPropsSelector (selectorFactory.js:63)
    at connectAdvanced.js:319
    at mountMemo (react-dom.development.js:15442)
    at Object.useMemo (react-dom.development.js:15738)
    at useMemo (react.development.js:1521)
    at ConnectFunction (connectAdvanced.js:304)
    at renderWithHooks (react-dom.development.js:14803)
    at updateFunctionComponent (react-dom.development.js:17034)
    at updateSimpleMemoComponent (react-dom.development.js:16972)
    at updateMemoComponent (react-dom.development.js:16861)
    at beginWork (react-dom.development.js:18682)
    at HTMLUnknownElement.callCallback (react-dom.development.js:188)
    at HTMLUnknownElement.sentryWrapped (helpers.js:71)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:237)
    at invokeGuardedCallback (react-dom.development.js:292)
    at beginWork$1 (react-dom.development.js:23203)
    at performUnitOfWork (react-dom.development.js:22157)
    at workLoopSync (react-dom.development.js:22130)
    at performSyncWorkOnRoot (react-dom.development.js:21756)
    at react-dom.development.js:11089
    at unstable_runWithPriority (scheduler.development.js:653)
    at runWithPriority$1 (react-dom.development.js:11039)
    at flushSyncCallbackQueueImpl (react-dom.development.js:11084)
    at flushSyncCallbackQueue (react-dom.development.js:11072)
    at discreteUpdates$1 (react-dom.development.js:21893)
    at discreteUpdates (react-dom.development.js:806)
    at dispatchDiscreteEvent (react-dom.development.js:4168)
    at HTMLDocument.sentryWrapped (helpers.js:71)
mapStateToProps @ LibraryPlaylists.js:360
mapToPropsProxy @ wrapMapToProps.js:41
detectFactoryAndVerify @ wrapMapToProps.js:50
mapToPropsProxy @ wrapMapToProps.js:41
handleFirstCall @ selectorFactory.js:22
pureFinalPropsSelector @ selectorFactory.js:63
(anonymous) @ connectAdvanced.js:319
mountMemo @ react-dom.development.js:15442
useMemo @ react-dom.development.js:15738
useMemo @ react.development.js:1521
ConnectFunction @ connectAdvanced.js:304
renderWithHooks @ react-dom.development.js:14803
updateFunctionComponent @ react-dom.development.js:17034
updateSimpleMemoComponent @ react-dom.development.js:16972
updateMemoComponent @ react-dom.development.js:16861
beginWork @ react-dom.development.js:18682
callCallback @ react-dom.development.js:188
sentryWrapped @ helpers.js:71
invokeGuardedCallbackDev @ react-dom.development.js:237
invokeGuardedCallback @ react-dom.development.js:292
beginWork$1 @ react-dom.development.js:23203
performUnitOfWork @ react-dom.development.js:22157
workLoopSync @ react-dom.development.js:22130
performSyncWorkOnRoot @ react-dom.development.js:21756
(anonymous) @ react-dom.development.js:11089
unstable_runWithPriority @ scheduler.development.js:653
runWithPriority$1 @ react-dom.development.js:11039
flushSyncCallbackQueueImpl @ react-dom.development.js:11084
flushSyncCallbackQueue @ react-dom.development.js:11072
discreteUpdates$1 @ react-dom.development.js:21893
discreteUpdates @ react-dom.development.js:806
dispatchDiscreteEvent @ react-dom.development.js:4168
sentryWrapped @ helpers.js:71
Show 3 more frames
instrument.js:110 The above error occurred in the <ConnectFunction> component:
    in ConnectFunction (created by Context.Consumer)
    in Route (created by App)
    in Switch (created by App)
    in main (created by App)
    in div (created by App)
    in Route (created by App)
    in Switch (created by App)
    in div (created by App)
    in div (created by App)
    in App (created by ConnectFunction)
    in ConnectFunction (created by Context.Consumer)
    in Route
    in Router (created by BrowserRouter)
    in BrowserRouter
    in PersistGate
    in Provider

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://fb.me/react-error-boundaries to learn more about error boundaries.
(anonymous) @ instrument.js:110
logCapturedError @ react-dom.development.js:19527
logError @ react-dom.development.js:19564
update.callback @ react-dom.development.js:20708
callCallback @ react-dom.development.js:12490
commitUpdateQueue @ react-dom.development.js:12511
commitLifeCycles @ react-dom.development.js:19883
commitLayoutEffects @ react-dom.development.js:22803
callCallback @ react-dom.development.js:188
sentryWrapped @ helpers.js:71
invokeGuardedCallbackDev @ react-dom.development.js:237
invokeGuardedCallback @ react-dom.development.js:292
commitRootImpl @ react-dom.development.js:22541
unstable_runWithPriority @ scheduler.development.js:653
runWithPriority$1 @ react-dom.development.js:11039
commitRoot @ react-dom.development.js:22381
finishSyncRender @ react-dom.development.js:21807
performSyncWorkOnRoot @ react-dom.development.js:21793
(anonymous) @ react-dom.development.js:11089
unstable_runWithPriority @ scheduler.development.js:653
runWithPriority$1 @ react-dom.development.js:11039
flushSyncCallbackQueueImpl @ react-dom.development.js:11084
flushSyncCallbackQueue @ react-dom.development.js:11072
discreteUpdates$1 @ react-dom.development.js:21893
discreteUpdates @ react-dom.development.js:806
dispatchDiscreteEvent @ react-dom.development.js:4168
sentryWrapped @ helpers.js:71
LibraryPlaylists.js:360 Uncaught TypeError: Cannot read property 'id' of null
    at Function.mapStateToProps [as mapToProps] (LibraryPlaylists.js:360)
    at mapToPropsProxy (wrapMapToProps.js:41)
    at Function.detectFactoryAndVerify (wrapMapToProps.js:50)
    at mapToPropsProxy (wrapMapToProps.js:41)
    at handleFirstCall (selectorFactory.js:22)
    at pureFinalPropsSelector (selectorFactory.js:63)
    at connectAdvanced.js:319
    at mountMemo (react-dom.development.js:15442)
    at Object.useMemo (react-dom.development.js:15738)
    at useMemo (react.development.js:1521)
    at ConnectFunction (connectAdvanced.js:304)
    at renderWithHooks (react-dom.development.js:14803)
    at updateFunctionComponent (react-dom.development.js:17034)
    at updateSimpleMemoComponent (react-dom.development.js:16972)
    at updateMemoComponent (react-dom.development.js:16861)
    at beginWork (react-dom.development.js:18682)
    at HTMLUnknownElement.callCallback (react-dom.development.js:188)
    at HTMLUnknownElement.sentryWrapped (helpers.js:71)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:237)
    at invokeGuardedCallback (react-dom.development.js:292)
    at beginWork$1 (react-dom.development.js:23203)
    at performUnitOfWork (react-dom.development.js:22157)
    at workLoopSync (react-dom.development.js:22130)
    at performSyncWorkOnRoot (react-dom.development.js:21756)
    at react-dom.development.js:11089
    at unstable_runWithPriority (scheduler.development.js:653)
    at runWithPriority$1 (react-dom.development.js:11039)
    at flushSyncCallbackQueueImpl (react-dom.development.js:11084)
    at flushSyncCallbackQueue (react-dom.development.js:11072)
    at discreteUpdates$1 (react-dom.development.js:21893)
    at discreteUpdates (react-dom.development.js:806)
    at dispatchDiscreteEvent (react-dom.development.js:4168)
    at HTMLDocument.sentryWrapped (helpers.js:71)
mapStateToProps @ LibraryPlaylists.js:360
mapToPropsProxy @ wrapMapToProps.js:41
detectFactoryAndVerify @ wrapMapToProps.js:50
mapToPropsProxy @ wrapMapToProps.js:41
handleFirstCall @ selectorFactory.js:22
pureFinalPropsSelector @ selectorFactory.js:63
(anonymous) @ connectAdvanced.js:319
mountMemo @ react-dom.development.js:15442
useMemo @ react-dom.development.js:15738
useMemo @ react.development.js:1521
ConnectFunction @ connectAdvanced.js:304
renderWithHooks @ react-dom.development.js:14803
updateFunctionComponent @ react-dom.development.js:17034
updateSimpleMemoComponent @ react-dom.development.js:16972
updateMemoComponent @ react-dom.development.js:16861
beginWork @ react-dom.development.js:18682
callCallback @ react-dom.development.js:188
sentryWrapped @ helpers.js:71
invokeGuardedCallbackDev @ react-dom.development.js:237
invokeGuardedCallback @ react-dom.development.js:292
beginWork$1 @ react-dom.development.js:23203
performUnitOfWork @ react-dom.development.js:22157
workLoopSync @ react-dom.development.js:22130
performSyncWorkOnRoot @ react-dom.development.js:21756
(anonymous) @ react-dom.development.js:11089
unstable_runWithPriority @ scheduler.development.js:653
runWithPriority$1 @ react-dom.development.js:11039
flushSyncCallbackQueueImpl @ react-dom.development.js:11084
flushSyncCallbackQueue @ react-dom.development.js:11072
discreteUpdates$1 @ react-dom.development.js:21893
discreteUpdates @ react-dom.development.js:806
dispatchDiscreteEvent @ react-dom.development.js:4168
sentryWrapped @ helpers.js:71
Show 3 more frames

**Comment by jaedb** [comment]
@LiranSX please try using your browser Incognito Mode to disable all caching of assets, and let me know if the issue persists.

**Comment by LiranSX** [comment]
with incognito mode the playlists are visible - so what needs to be done to make it work with non incognito?

**Comment by jaedb** [comment]
You need to completely reset your browser of Iris data. Follow the instructions on https://www.howtogeek.com/664912/how-to-clear-storage-and-site-data-for-a-single-site-on-google-chrome/ for Chrome, or https://www.refreshyourcache.com for general directions.
