### ISSUE TITLE
first load of every page is blank

### ISSUE THREAD

**Issue by LiranSX** [jaedb/Iris#669]
scenario:
iris version 3.55.1, chrome latest on windows
1. open chrome in incognito mode
2. click on "Save" for "Welcome to Iris" page
3. the page is blank. need to refresh it to see something
4. click on anything from the left menu for example "browse" -> blank page need to refresh again to see it.
debug log attached
5. this happens on non incognito mode also but did it this way to make sure no chaching etc.

**console log with debug mode for step 2:**

analytics.js:1 Failed to load resource: net::ERR_NAME_NOT_RESOLVED
app.min.js?v=1606811555:111 TypeError: Cannot read property '0' of undefined
    at value (app.min.js?v=1606811555:111)
    at ho (app.min.js?v=1606811555:78)
    at go (app.min.js?v=1606811555:78)
    at Mi (app.min.js?v=1606811555:78)
    at yc (app.min.js?v=1606811555:78)
    at us (app.min.js?v=1606811555:78)
    at cs (app.min.js?v=1606811555:78)
    at $c (app.min.js?v=1606811555:78)
    at app.min.js?v=1606811555:78
    at t.unstable_runWithPriority (app.min.js?v=1606811555:86)
    at Ha (app.min.js?v=1606811555:78)
    at Wa (app.min.js?v=1606811555:78)
    at Va (app.min.js?v=1606811555:78)
    at I (app.min.js?v=1606811555:78)
    at Qt (app.min.js?v=1606811555:78)
    at HTMLDocument.r (app.min.js?v=1606811555:111)
(anonymous) @ app.min.js?v=1606811555:111
ec @ app.min.js?v=1606811555:78
n.callback @ app.min.js?v=1606811555:78
fo @ app.min.js?v=1606811555:78
oc @ app.min.js?v=1606811555:78
ds @ app.min.js?v=1606811555:78
t.unstable_runWithPriority @ app.min.js?v=1606811555:86
Ha @ app.min.js?v=1606811555:78
ps @ app.min.js?v=1606811555:78
$c @ app.min.js?v=1606811555:78
(anonymous) @ app.min.js?v=1606811555:78
t.unstable_runWithPriority @ app.min.js?v=1606811555:86
Ha @ app.min.js?v=1606811555:78
Wa @ app.min.js?v=1606811555:78
Va @ app.min.js?v=1606811555:78
I @ app.min.js?v=1606811555:78
Qt @ app.min.js?v=1606811555:78
r @ app.min.js?v=1606811555:111
app.min.js?v=1606811555:111 Uncaught TypeError: Cannot read property '0' of undefined
    at value (app.min.js?v=1606811555:111)
    at ho (app.min.js?v=1606811555:78)
    at go (app.min.js?v=1606811555:78)
    at Mi (app.min.js?v=1606811555:78)
    at yc (app.min.js?v=1606811555:78)
    at us (app.min.js?v=1606811555:78)
    at cs (app.min.js?v=1606811555:78)
    at $c (app.min.js?v=1606811555:78)
    at app.min.js?v=1606811555:78
    at t.unstable_runWithPriority (app.min.js?v=1606811555:86)
    at Ha (app.min.js?v=1606811555:78)
    at Wa (app.min.js?v=1606811555:78)
    at Va (app.min.js?v=1606811555:78)
    at I (app.min.js?v=1606811555:78)
    at Qt (app.min.js?v=1606811555:78)
    at HTMLDocument.r (app.min.js?v=1606811555:111)
value @ app.min.js?v=1606811555:111
ho @ app.min.js?v=1606811555:78
go @ app.min.js?v=1606811555:78
Mi @ app.min.js?v=1606811555:78
yc @ app.min.js?v=1606811555:78
us @ app.min.js?v=1606811555:78
cs @ app.min.js?v=1606811555:78
$c @ app.min.js?v=1606811555:78
(anonymous) @ app.min.js?v=1606811555:78
t.unstable_runWithPriority @ app.min.js?v=1606811555:86
Ha @ app.min.js?v=1606811555:78
Wa @ app.min.js?v=1606811555:78
Va @ app.min.js?v=1606811555:78
I @ app.min.js?v=1606811555:78
Qt @ app.min.js?v=1606811555:78
r @ app.min.js?v=1606811555:111 

**console log with debug mode for step 4:**
MediaSession.js:32 Uncaught TypeError: Cannot read property '0' of undefined
    at getDerivedStateFromProps (MediaSession.js:32)
    at applyDerivedStateFromProps (react-dom.development.js:12603)
    at mountClassInstance (react-dom.development.js:13041)
    at updateClassComponent (react-dom.development.js:17101)
    at beginWork (react-dom.development.js:18620)
    at HTMLUnknownElement.callCallback (react-dom.development.js:188)
    at HTMLUnknownElement.sentryWrapped (helpers.js:72)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:237)
    at invokeGuardedCallback (react-dom.development.js:292)
    at beginWork$1 (react-dom.development.js:23203)
    at performUnitOfWork (react-dom.development.js:22157)
    at workLoopSync (react-dom.development.js:22130)
    at performSyncWorkOnRoot (react-dom.development.js:21756)
    at react-dom.development.js:11089
    at unstable_runWithPriority (scheduler.development.js:653)
    at runWithPriority$1 (react-dom.development.js:11039)
    at flushSyncCallbackQueueImpl (react-dom.development.js:11084)
    at flushSyncCallbackQueue (react-dom.development.js:11072)
    at discreteUpdates$1 (react-dom.development.js:21893)
    at discreteUpdates (react-dom.development.js:806)
    at dispatchDiscreteEvent (react-dom.development.js:4168)
    at HTMLDocument.sentryWrapped (helpers.js:72)
getDerivedStateFromProps @ MediaSession.js:32
applyDerivedStateFromProps @ react-dom.development.js:12603
mountClassInstance @ react-dom.development.js:13041
updateClassComponent @ react-dom.development.js:17101
beginWork @ react-dom.development.js:18620
callCallback @ react-dom.development.js:188
sentryWrapped @ helpers.js:72
invokeGuardedCallbackDev @ react-dom.development.js:237
invokeGuardedCallback @ react-dom.development.js:292
beginWork$1 @ react-dom.development.js:23203
performUnitOfWork @ react-dom.development.js:22157
workLoopSync @ react-dom.development.js:22130
performSyncWorkOnRoot @ react-dom.development.js:21756
(anonymous) @ react-dom.development.js:11089
unstable_runWithPriority @ scheduler.development.js:653
runWithPriority$1 @ react-dom.development.js:11039
flushSyncCallbackQueueImpl @ react-dom.development.js:11084
flushSyncCallbackQueue @ react-dom.development.js:11072
discreteUpdates$1 @ react-dom.development.js:21893
discreteUpdates @ react-dom.development.js:806
dispatchDiscreteEvent @ react-dom.development.js:4168
sentryWrapped @ helpers.js:72
instrument.js:109 The above error occurred in the <MediaSession> component:
    in MediaSession (created by ConnectFunction)
    in ConnectFunction (created by App)
    in div (created by App)
    in App (created by ConnectFunction)
    in ConnectFunction (created by Context.Consumer)
    in Route
    in Router (created by BrowserRouter)
    in BrowserRouter
    in PersistGate
    in Provider

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://fb.me/react-error-boundaries to learn more about error boundaries.
(anonymous) @ instrument.js:109
logCapturedError @ react-dom.development.js:19527
logError @ react-dom.development.js:19564
update.callback @ react-dom.development.js:20708
callCallback @ react-dom.development.js:12490
commitUpdateQueue @ react-dom.development.js:12511
commitLifeCycles @ react-dom.development.js:19883
commitLayoutEffects @ react-dom.development.js:22803
callCallback @ react-dom.development.js:188
sentryWrapped @ helpers.js:72
invokeGuardedCallbackDev @ react-dom.development.js:237
invokeGuardedCallback @ react-dom.development.js:292
commitRootImpl @ react-dom.development.js:22541
unstable_runWithPriority @ scheduler.development.js:653
runWithPriority$1 @ react-dom.development.js:11039
commitRoot @ react-dom.development.js:22381
finishSyncRender @ react-dom.development.js:21807
performSyncWorkOnRoot @ react-dom.development.js:21793
(anonymous) @ react-dom.development.js:11089
unstable_runWithPriority @ scheduler.development.js:653
runWithPriority$1 @ react-dom.development.js:11039
flushSyncCallbackQueueImpl @ react-dom.development.js:11084
flushSyncCallbackQueue @ react-dom.development.js:11072
discreteUpdates$1 @ react-dom.development.js:21893
discreteUpdates @ react-dom.development.js:806
dispatchDiscreteEvent @ react-dom.development.js:4168
sentryWrapped @ helpers.js:72
MediaSession.js:32 Uncaught TypeError: Cannot read property '0' of undefined
    at getDerivedStateFromProps (MediaSession.js:32)
    at applyDerivedStateFromProps (react-dom.development.js:12603)
    at mountClassInstance (react-dom.development.js:13041)
    at updateClassComponent (react-dom.development.js:17101)
    at beginWork (react-dom.development.js:18620)
    at HTMLUnknownElement.callCallback (react-dom.development.js:188)
    at HTMLUnknownElement.sentryWrapped (helpers.js:72)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:237)
    at invokeGuardedCallback (react-dom.development.js:292)
    at beginWork$1 (react-dom.development.js:23203)
    at performUnitOfWork (react-dom.development.js:22157)
    at workLoopSync (react-dom.development.js:22130)
    at performSyncWorkOnRoot (react-dom.development.js:21756)
    at react-dom.development.js:11089
    at unstable_runWithPriority (scheduler.development.js:653)
    at runWithPriority$1 (react-dom.development.js:11039)
    at flushSyncCallbackQueueImpl (react-dom.development.js:11084)
    at flushSyncCallbackQueue (react-dom.development.js:11072)
    at discreteUpdates$1 (react-dom.development.js:21893)
    at discreteUpdates (react-dom.development.js:806)
    at dispatchDiscreteEvent (react-dom.development.js:4168)
    at HTMLDocument.sentryWrapped (helpers.js:72)
getDerivedStateFromProps @ MediaSession.js:32
applyDerivedStateFromProps @ react-dom.development.js:12603
mountClassInstance @ react-dom.development.js:13041
updateClassComponent @ react-dom.development.js:17101
beginWork @ react-dom.development.js:18620
callCallback @ react-dom.development.js:188
sentryWrapped @ helpers.js:72
invokeGuardedCallbackDev @ react-dom.development.js:237
invokeGuardedCallback @ react-dom.development.js:292
beginWork$1 @ react-dom.development.js:23203
performUnitOfWork @ react-dom.development.js:22157
workLoopSync @ react-dom.development.js:22130
performSyncWorkOnRoot @ react-dom.development.js:21756
(anonymous) @ react-dom.development.js:11089
unstable_runWithPriority @ scheduler.development.js:653
runWithPriority$1 @ react-dom.development.js:11039
flushSyncCallbackQueueImpl @ react-dom.development.js:11084
flushSyncCallbackQueue @ react-dom.development.js:11072
discreteUpdates$1 @ react-dom.development.js:21893
discreteUpdates @ react-dom.development.js:806
dispatchDiscreteEvent @ react-dom.development.js:4168
sentryWrapped @ helpers.js:72
libflac.js:104 POST https://o99789.ingest.sentry.io/api/219026/store/?sentry_key=ca99fb6662fe40ae8ec4c18a466e4b4b&sentry_version=7 429 (Too Many Requests)
global.fetch @ libflac.js:104
(anonymous) @ instrument.js:136
(anonymous) @ fetch.js:55
SyncPromise @ syncpromise.js:78
./node_modules/@sentry/browser/esm/transports/fetch.js.FetchTransport._sendRequest @ fetch.js:53
./node_modules/@sentry/browser/esm/transports/fetch.js.FetchTransport.sendEvent @ fetch.js:16
./node_modules/@sentry/core/esm/basebackend.js.BaseBackend.sendEvent @ basebackend.js:33
./node_modules/@sentry/core/esm/baseclient.js.BaseClient._sendEvent @ baseclient.js:361
./node_modules/@sentry/browser/esm/client.js.BrowserClient._sendEvent @ client.js:64
(anonymous) @ baseclient.js:432
onfulfilled @ syncpromise.js:137
(anonymous) @ syncpromise.js:66
SyncPromise._executeHandlers @ syncpromise.js:59
SyncPromise._attachHandler @ syncpromise.js:50
(anonymous) @ syncpromise.js:127
SyncPromise @ syncpromise.js:78
./node_modules/@sentry/utils/esm/syncpromise.js.SyncPromise.then @ syncpromise.js:126
./node_modules/@sentry/core/esm/baseclient.js.BaseClient._processEvent @ baseclient.js:424
./node_modules/@sentry/core/esm/baseclient.js.BaseClient._captureEvent @ baseclient.js:370
(anonymous) @ baseclient.js:66
onfulfilled @ syncpromise.js:137
(anonymous) @ syncpromise.js:66
SyncPromise._executeHandlers @ syncpromise.js:59
SyncPromise._attachHandler @ syncpromise.js:50
(anonymous) @ syncpromise.js:127
SyncPromise @ syncpromise.js:78
./node_modules/@sentry/utils/esm/syncpromise.js.SyncPromise.then @ syncpromise.js:126
./node_modules/@sentry/core/esm/baseclient.js.BaseClient.captureException @ baseclient.js:66
./node_modules/@sentry/hub/esm/hub.js.Hub._invokeClient @ hub.js:348
./node_modules/@sentry/hub/esm/hub.js.Hub.captureException @ hub.js:135
callOnHub @ index.js:17
captureException @ index.js:36
(anonymous) @ helpers.js:86
./node_modules/@sentry/hub/esm/hub.js.Hub.withScope @ hub.js:87
callOnHub @ index.js:17
withScope @ index.js:151
sentryWrapped @ helpers.js:76
invokeGuardedCallbackDev @ react-dom.development.js:237
invokeGuardedCallback @ react-dom.development.js:292
beginWork$1 @ react-dom.development.js:23203
performUnitOfWork @ react-dom.development.js:22157
workLoopSync @ react-dom.development.js:22130
performSyncWorkOnRoot @ react-dom.development.js:21756
(anonymous) @ react-dom.development.js:11089
unstable_runWithPriority @ scheduler.development.js:653
runWithPriority$1 @ react-dom.development.js:11039
flushSyncCallbackQueueImpl @ react-dom.development.js:11084
flushSyncCallbackQueue @ react-dom.development.js:11072
discreteUpdates$1 @ react-dom.development.js:21893
discreteUpdates @ react-dom.development.js:806
dispatchDiscreteEvent @ react-dom.development.js:4168
sentryWrapped @ helpers.js:72
Show 22 more frames

**Comment by morithil** [comment]
I am also experiencing this

**Comment by jaedb** [comment]
This was resolved in the latest release. Remember to clear all settings/cache in your browser after upgrading.

**Comment by LiranSX** [comment]
i wan't resolved - sorry. in chrome -> settings -> "Clear browsing data" -> Advanced - marked ALL and clicked "clear data". then browsing to "http://[ip]:6680/iris/" the main page is displayed, but click on "playlists" for example -> get a blank page with this error:

react-dom.development.js:24994 Download the React DevTools for a better development experience: https://fb.me/react-devtools
autoMergeLevel1.js:35 redux-persist/stateReconciler: rehydrated keys 'mopidy, lastfm, genius, google, snapcast, _persist'
autoMergeLevel1.js:35 redux-persist/stateReconciler: rehydrated keys 'outputs, queue, queue_metadata, current_track, pinned, http_streaming_enabled, http_streaming_cachebuster, http_streaming_url, current_track_uri, seeds_resolved, radio, current_tracklist, next_track_uri, _persist'
autoMergeLevel1.js:35 redux-persist/stateReconciler: rehydrated keys 'language, theme, smooth_scrolling_enabled, hotkeys_enabled, playback_controls_touch_enabled, allow_reporting, wide_scrollbar_enabled, slim_mode, suppressed_broadcasts, grid_glow_enabled, window_title, uri_schemes_search_enabled, initial_setup_complete, _persist'
autoMergeLevel1.js:35 redux-persist/stateReconciler: rehydrated keys 'host, port, ssl, current_server, servers, mute, volume, play_state, uri_schemes, library_albums_uri, library_artists_uri, consume, random, repeat, _persist'
autoMergeLevel1.js:35 redux-persist/stateReconciler: rehydrated keys 'me, enabled, country, locale, _persist'
autoMergeLevel1.js:35 redux-persist/stateReconciler: rehydrated keys 'connected, username, client_id, version, config, connecting, commands, pinned, upgrading, connection_id, _persist'
LibraryPlaylists.js:360 Uncaught TypeError: Cannot read property 'id' of null
    at Function.mapStateToProps [as mapToProps] (LibraryPlaylists.js:360)
    at mapToPropsProxy (wrapMapToProps.js:41)
    at Function.detectFactoryAndVerify (wrapMapToProps.js:50)
    at mapToPropsProxy (wrapMapToProps.js:41)
    at handleFirstCall (selectorFactory.js:22)
    at pureFinalPropsSelector (selectorFactory.js:63)
    at connectAdvanced.js:319
    at mountMemo (react-dom.development.js:15442)
    at Object.useMemo (react-dom.development.js:15738)
    at useMemo (react.development.js:1521)
    at ConnectFunction (connectAdvanced.js:304)
    at renderWithHooks (react-dom.development.js:14803)
    at updateFunctionComponent (react-dom.development.js:17034)
    at updateSimpleMemoComponent (react-dom.development.js:16972)
    at updateMemoComponent (react-dom.development.js:16861)
    at beginWork (react-dom.development.js:18682)
    at HTMLUnknownElement.callCallback (react-dom.development.js:188)
    at HTMLUnknownElement.sentryWrapped (helpers.js:72)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:237)
    at invokeGuardedCallback (react-dom.development.js:292)
    at beginWork$1 (react-dom.development.js:23203)
    at performUnitOfWork (react-dom.development.js:22157)
    at workLoopSync (react-dom.development.js:22130)
    at performSyncWorkOnRoot (react-dom.development.js:21756)
    at react-dom.development.js:11089
    at unstable_runWithPriority (scheduler.development.js:653)
    at runWithPriority$1 (react-dom.development.js:11039)
    at flushSyncCallbackQueueImpl (react-dom.development.js:11084)
    at flushSyncCallbackQueue (react-dom.development.js:11072)
    at scheduleUpdateOnFiber (react-dom.development.js:21199)
    at Object.enqueueSetState (react-dom.development.js:12639)
    at PersistGate../node_modules/react/cjs/react.development.js.Component.setState (react.development.js:471)
    at react.js:61
    at Object.dispatch (redux.js:222)
    at Object.rehydrate (persistStore.js:79)
    at _rehydrate (persistReducer.js:61)
    at persistReducer.js:90
mapStateToProps @ LibraryPlaylists.js:360
mapToPropsProxy @ wrapMapToProps.js:41
detectFactoryAndVerify @ wrapMapToProps.js:50
mapToPropsProxy @ wrapMapToProps.js:41
handleFirstCall @ selectorFactory.js:22
pureFinalPropsSelector @ selectorFactory.js:63
(anonymous) @ connectAdvanced.js:319
mountMemo @ react-dom.development.js:15442
useMemo @ react-dom.development.js:15738
useMemo @ react.development.js:1521
ConnectFunction @ connectAdvanced.js:304
renderWithHooks @ react-dom.development.js:14803
updateFunctionComponent @ react-dom.development.js:17034
updateSimpleMemoComponent @ react-dom.development.js:16972
updateMemoComponent @ react-dom.development.js:16861
beginWork @ react-dom.development.js:18682
callCallback @ react-dom.development.js:188
sentryWrapped @ helpers.js:72
invokeGuardedCallbackDev @ react-dom.development.js:237
invokeGuardedCallback @ react-dom.development.js:292
beginWork$1 @ react-dom.development.js:23203
performUnitOfWork @ react-dom.development.js:22157
workLoopSync @ react-dom.development.js:22130
performSyncWorkOnRoot @ react-dom.development.js:21756
(anonymous) @ react-dom.development.js:11089
unstable_runWithPriority @ scheduler.development.js:653
runWithPriority$1 @ react-dom.development.js:11039
flushSyncCallbackQueueImpl @ react-dom.development.js:11084
flushSyncCallbackQueue @ react-dom.development.js:11072
scheduleUpdateOnFiber @ react-dom.development.js:21199
enqueueSetState @ react-dom.development.js:12639
./node_modules/react/cjs/react.development.js.Component.setState @ react.development.js:471
(anonymous) @ react.js:61
dispatch @ redux.js:222
rehydrate @ persistStore.js:79
_rehydrate @ persistReducer.js:61
(anonymous) @ persistReducer.js:90
Promise.then (async)
(anonymous) @ persistReducer.js:89
Promise.then (async)
(anonymous) @ persistReducer.js:84
combination @ redux.js:459
rootReducer @ index.js:247
(anonymous) @ persistReducer.js:99
dispatch @ redux.js:213
(anonymous) @ middleware.js:643
(anonymous) @ middleware.js:162
(anonymous) @ middleware.js:53
(anonymous) @ middleware.js:55
(anonymous) @ middleware.js:203
(anonymous) @ middleware.js:886
(anonymous) @ middleware.js:1933
(anonymous) @ middleware.js:238
(anonymous) @ middleware.js:765
(anonymous) @ index.js:11
persist @ persistStore.js:114
persistStore @ persistStore.js:123
./src/js/store/index.js @ index.js:268
__webpack_require__ @ bootstrap:19
./src/js/index.js @ index.js:2
__webpack_require__ @ bootstrap:19
0 @ app.scss?3f94:7
__webpack_require__ @ bootstrap:19
(anonymous) @ bootstrap:83
(anonymous) @ bootstrap:83
Show 7 more frames
instrument.js:109 The above error occurred in the <ConnectFunction> component:
    in ConnectFunction (created by Context.Consumer)
    in Route (created by App)
    in Switch (created by App)
    in main (created by App)
    in div (created by App)
    in Route (created by App)
    in Switch (created by App)
    in div (created by App)
    in div (created by App)
    in App (created by ConnectFunction)
    in ConnectFunction (created by Context.Consumer)
    in Route
    in Router (created by BrowserRouter)
    in BrowserRouter
    in PersistGate
    in Provider

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://fb.me/react-error-boundaries to learn more about error boundaries.
(anonymous) @ instrument.js:109
logCapturedError @ react-dom.development.js:19527
logError @ react-dom.development.js:19564
update.callback @ react-dom.development.js:20708
callCallback @ react-dom.development.js:12490
commitUpdateQueue @ react-dom.development.js:12511
commitLifeCycles @ react-dom.development.js:19883
commitLayoutEffects @ react-dom.development.js:22803
callCallback @ react-dom.development.js:188
sentryWrapped @ helpers.js:72
invokeGuardedCallbackDev @ react-dom.development.js:237
invokeGuardedCallback @ react-dom.development.js:292
commitRootImpl @ react-dom.development.js:22541
unstable_runWithPriority @ scheduler.development.js:653
runWithPriority$1 @ react-dom.development.js:11039
commitRoot @ react-dom.development.js:22381
finishSyncRender @ react-dom.development.js:21807
performSyncWorkOnRoot @ react-dom.development.js:21793
(anonymous) @ react-dom.development.js:11089
unstable_runWithPriority @ scheduler.development.js:653
runWithPriority$1 @ react-dom.development.js:11039
flushSyncCallbackQueueImpl @ react-dom.development.js:11084
flushSyncCallbackQueue @ react-dom.development.js:11072
scheduleUpdateOnFiber @ react-dom.development.js:21199
enqueueSetState @ react-dom.development.js:12639
./node_modules/react/cjs/react.development.js.Component.setState @ react.development.js:471
(anonymous) @ react.js:61
dispatch @ redux.js:222
rehydrate @ persistStore.js:79
_rehydrate @ persistReducer.js:61
(anonymous) @ persistReducer.js:90
Promise.then (async)
(anonymous) @ persistReducer.js:89
Promise.then (async)
(anonymous) @ persistReducer.js:84
combination @ redux.js:459
rootReducer @ index.js:247
(anonymous) @ persistReducer.js:99
dispatch @ redux.js:213
(anonymous) @ middleware.js:643
(anonymous) @ middleware.js:162
(anonymous) @ middleware.js:53
(anonymous) @ middleware.js:55
(anonymous) @ middleware.js:203
(anonymous) @ middleware.js:886
(anonymous) @ middleware.js:1933
(anonymous) @ middleware.js:238
(anonymous) @ middleware.js:765
(anonymous) @ index.js:11
persist @ persistStore.js:114
persistStore @ persistStore.js:123
./src/js/store/index.js @ index.js:268
__webpack_require__ @ bootstrap:19
./src/js/index.js @ index.js:2
__webpack_require__ @ bootstrap:19
0 @ app.scss?3f94:7
__webpack_require__ @ bootstrap:19
(anonymous) @ bootstrap:83
(anonymous) @ bootstrap:83
loadGA.js:26 GET https://www.google-analytics.com/analytics.js net::ERR_NAME_NOT_RESOLVED
(anonymous) @ loadGA.js:26
(anonymous) @ loadGA.js:27
initialize @ core.js:143
App @ App.js:76
constructClassInstance @ react-dom.development.js:12880
updateClassComponent @ react-dom.development.js:17100
beginWork @ react-dom.development.js:18620
beginWork$1 @ react-dom.development.js:23179
performUnitOfWork @ react-dom.development.js:22157
workLoopSync @ react-dom.development.js:22130
performSyncWorkOnRoot @ react-dom.development.js:21756
(anonymous) @ react-dom.development.js:11089
unstable_runWithPriority @ scheduler.development.js:653
runWithPriority$1 @ react-dom.development.js:11039
flushSyncCallbackQueueImpl @ react-dom.development.js:11084
flushSyncCallbackQueue @ react-dom.development.js:11072
scheduleUpdateOnFiber @ react-dom.development.js:21199
enqueueSetState @ react-dom.development.js:12639
./node_modules/react/cjs/react.development.js.Component.setState @ react.development.js:471
(anonymous) @ react.js:61
dispatch @ redux.js:222
rehydrate @ persistStore.js:79
_rehydrate @ persistReducer.js:61
(anonymous) @ persistReducer.js:90
Promise.then (async)
(anonymous) @ persistReducer.js:89
Promise.then (async)
(anonymous) @ persistReducer.js:84
combination @ redux.js:459
rootReducer @ index.js:247
(anonymous) @ persistReducer.js:99
dispatch @ redux.js:213
(anonymous) @ middleware.js:643
(anonymous) @ middleware.js:162
(anonymous) @ middleware.js:53
(anonymous) @ middleware.js:55
(anonymous) @ middleware.js:203
(anonymous) @ middleware.js:886
(anonymous) @ middleware.js:1933
(anonymous) @ middleware.js:238
(anonymous) @ middleware.js:765
(anonymous) @ index.js:11
persist @ persistStore.js:114
persistStore @ persistStore.js:123
./src/js/store/index.js @ index.js:268
__webpack_require__ @ bootstrap:19
./src/js/index.js @ index.js:2
__webpack_require__ @ bootstrap:19
0 @ app.scss?3f94:7
__webpack_require__ @ bootstrap:19
(anonymous) @ bootstrap:83
(anonymous) @ bootstrap:83
LibraryPlaylists.js:360 Uncaught (in promise) TypeError: Cannot read property 'id' of null
    at Function.mapStateToProps [as mapToProps] (LibraryPlaylists.js:360)
    at mapToPropsProxy (wrapMapToProps.js:41)
    at Function.detectFactoryAndVerify (wrapMapToProps.js:50)
    at mapToPropsProxy (wrapMapToProps.js:41)
    at handleFirstCall (selectorFactory.js:22)
    at pureFinalPropsSelector (selectorFactory.js:63)
    at connectAdvanced.js:319
    at mountMemo (react-dom.development.js:15442)
    at Object.useMemo (react-dom.development.js:15738)
    at useMemo (react.development.js:1521)
    at ConnectFunction (connectAdvanced.js:304)
    at renderWithHooks (react-dom.development.js:14803)
    at updateFunctionComponent (react-dom.development.js:17034)
    at updateSimpleMemoComponent (react-dom.development.js:16972)
    at updateMemoComponent (react-dom.development.js:16861)
    at beginWork (react-dom.development.js:18682)
    at HTMLUnknownElement.callCallback (react-dom.development.js:188)
    at HTMLUnknownElement.sentryWrapped (helpers.js:72)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:237)
    at invokeGuardedCallback (react-dom.development.js:292)
    at beginWork$1 (react-dom.development.js:23203)
    at performUnitOfWork (react-dom.development.js:22157)
    at workLoopSync (react-dom.development.js:22130)
    at performSyncWorkOnRoot (react-dom.development.js:21756)
    at react-dom.development.js:11089
    at unstable_runWithPriority (scheduler.development.js:653)
    at runWithPriority$1 (react-dom.development.js:11039)
    at flushSyncCallbackQueueImpl (react-dom.development.js:11084)
    at flushSyncCallbackQueue (react-dom.development.js:11072)
    at scheduleUpdateOnFiber (react-dom.development.js:21199)
    at Object.enqueueSetState (react-dom.development.js:12639)
    at PersistGate../node_modules/react/cjs/react.development.js.Component.setState (react.development.js:471)
    at react.js:61
    at Object.dispatch (redux.js:222)
    at Object.rehydrate (persistStore.js:79)
    at _rehydrate (persistReducer.js:61)
    at persistReducer.js:90
mapStateToProps @ LibraryPlaylists.js:360
mapToPropsProxy @ wrapMapToProps.js:41
detectFactoryAndVerify @ wrapMapToProps.js:50
mapToPropsProxy @ wrapMapToProps.js:41
handleFirstCall @ selectorFactory.js:22
pureFinalPropsSelector @ selectorFactory.js:63
(anonymous) @ connectAdvanced.js:319
mountMemo @ react-dom.development.js:15442
useMemo @ react-dom.development.js:15738
useMemo @ react.development.js:1521
ConnectFunction @ connectAdvanced.js:304
renderWithHooks @ react-dom.development.js:14803
updateFunctionComponent @ react-dom.development.js:17034
updateSimpleMemoComponent @ react-dom.development.js:16972
updateMemoComponent @ react-dom.development.js:16861
beginWork @ react-dom.development.js:18682
callCallback @ react-dom.development.js:188
sentryWrapped @ helpers.js:72
invokeGuardedCallbackDev @ react-dom.development.js:237
invokeGuardedCallback @ react-dom.development.js:292
beginWork$1 @ react-dom.development.js:23203
performUnitOfWork @ react-dom.development.js:22157
workLoopSync @ react-dom.development.js:22130
performSyncWorkOnRoot @ react-dom.development.js:21756
(anonymous) @ react-dom.development.js:11089
unstable_runWithPriority @ scheduler.development.js:653
runWithPriority$1 @ react-dom.development.js:11039
flushSyncCallbackQueueImpl @ react-dom.development.js:11084
flushSyncCallbackQueue @ react-dom.development.js:11072
scheduleUpdateOnFiber @ react-dom.development.js:21199
enqueueSetState @ react-dom.development.js:12639
./node_modules/react/cjs/react.development.js.Component.setState @ react.development.js:471
(anonymous) @ react.js:61
dispatch @ redux.js:222
rehydrate @ persistStore.js:79
_rehydrate @ persistReducer.js:61
(anonymous) @ persistReducer.js:90
Promise.then (async)
(anonymous) @ persistReducer.js:89
Promise.then (async)
(anonymous) @ persistReducer.js:84
combination @ redux.js:459
rootReducer @ index.js:247
(anonymous) @ persistReducer.js:99
dispatch @ redux.js:213
(anonymous) @ middleware.js:643
(anonymous) @ middleware.js:162
(anonymous) @ middleware.js:53
(anonymous) @ middleware.js:55
(anonymous) @ middleware.js:203
(anonymous) @ middleware.js:886
(anonymous) @ middleware.js:1933
(anonymous) @ middleware.js:238
(anonymous) @ middleware.js:765
(anonymous) @ index.js:11
persist @ persistStore.js:114
persistStore @ persistStore.js:123
./src/js/store/index.js @ index.js:268
__webpack_require__ @ bootstrap:19
./src/js/index.js @ index.js:2
__webpack_require__ @ bootstrap:19
0 @ app.scss?3f94:7
__webpack_require__ @ bootstrap:19
(anonymous) @ bootstrap:83
(anonymous) @ bootstrap:83
Show 7 more frames

**Comment by LiranSX** [comment]
It wasn't resolved – see my last comment there please.

**Comment by LiranSX** [comment]
this is still reproducible with version 3.55.2

this is the error in the console after clearing ALL browsing data + restarting in chrome:

app.min.js?v=1607625587:16 GET https://www.google-analytics.com/analytics.js net::ERR_NAME_NOT_RESOLVED
(anonymous) @ app.min.js?v=1607625587:16
W @ app.min.js?v=1607625587:16
i @ app.min.js?v=1607625587:111
vo @ app.min.js?v=1607625587:78
Mi @ app.min.js?v=1607625587:78
yc @ app.min.js?v=1607625587:78
us @ app.min.js?v=1607625587:78
cs @ app.min.js?v=1607625587:78
$c @ app.min.js?v=1607625587:78
(anonymous) @ app.min.js?v=1607625587:78
t.unstable_runWithPriority @ app.min.js?v=1607625587:86
Ha @ app.min.js?v=1607625587:78
Wa @ app.min.js?v=1607625587:78
Va @ app.min.js?v=1607625587:78
Kc @ app.min.js?v=1607625587:78
enqueueSetState @ app.min.js?v=1607625587:78
g.setState @ app.min.js?v=1607625587:70
(anonymous) @ app.min.js?v=1607625587:111
y @ app.min.js?v=1607625587:1
Cn @ app.min.js?v=1607625587:111
y @ app.min.js?v=1607625587:111
(anonymous) @ app.min.js?v=1607625587:111
Promise.then (async)
(anonymous) @ app.min.js?v=1607625587:111
Promise.then (async)
(anonymous) @ app.min.js?v=1607625587:111
(anonymous) @ app.min.js?v=1607625587:1
(anonymous) @ app.min.js?v=1607625587:111
(anonymous) @ app.min.js?v=1607625587:111
y @ app.min.js?v=1607625587:1
(anonymous) @ app.min.js?v=1607625587:111
(anonymous) @ app.min.js?v=1607625587:111
(anonymous) @ app.min.js?v=1607625587:111
(anonymous) @ app.min.js?v=1607625587:111
(anonymous) @ app.min.js?v=1607625587:111
(anonymous) @ app.min.js?v=1607625587:111
(anonymous) @ app.min.js?v=1607625587:111
(anonymous) @ app.min.js?v=1607625587:62
(anonymous) @ app.min.js?v=1607625587:111
(anonymous) @ app.min.js?v=1607625587:111
persist @ app.min.js?v=1607625587:111
(anonymous) @ app.min.js?v=1607625587:111
n @ app.min.js?v=1607625587:1
(anonymous) @ app.min.js?v=1607625587:62
n @ app.min.js?v=1607625587:1
(anonymous) @ app.min.js?v=1607625587:1
(anonymous) @ app.min.js?v=1607625587:1
app.min.js?v=1607625587:111 TypeError: Cannot read property '0' of undefined
    at value (app.min.js?v=1607625587:111)
    at ho (app.min.js?v=1607625587:78)
    at go (app.min.js?v=1607625587:78)
    at Mi (app.min.js?v=1607625587:78)
    at yc (app.min.js?v=1607625587:78)
    at us (app.min.js?v=1607625587:78)
    at cs (app.min.js?v=1607625587:78)
    at $c (app.min.js?v=1607625587:78)
    at app.min.js?v=1607625587:78
    at t.unstable_runWithPriority (app.min.js?v=1607625587:86)
    at Ha (app.min.js?v=1607625587:78)
    at Wa (app.min.js?v=1607625587:78)
    at Va (app.min.js?v=1607625587:78)
    at I (app.min.js?v=1607625587:78)
    at Qt (app.min.js?v=1607625587:78)
    at HTMLDocument.r (app.min.js?v=1607625587:111)
(anonymous) @ app.min.js?v=1607625587:111
ec @ app.min.js?v=1607625587:78
n.callback @ app.min.js?v=1607625587:78
fo @ app.min.js?v=1607625587:78
oc @ app.min.js?v=1607625587:78
ds @ app.min.js?v=1607625587:78
t.unstable_runWithPriority @ app.min.js?v=1607625587:86
Ha @ app.min.js?v=1607625587:78
ps @ app.min.js?v=1607625587:78
$c @ app.min.js?v=1607625587:78
(anonymous) @ app.min.js?v=1607625587:78
t.unstable_runWithPriority @ app.min.js?v=1607625587:86
Ha @ app.min.js?v=1607625587:78
Wa @ app.min.js?v=1607625587:78
Va @ app.min.js?v=1607625587:78
I @ app.min.js?v=1607625587:78
Qt @ app.min.js?v=1607625587:78
r @ app.min.js?v=1607625587:111
app.min.js?v=1607625587:111 Uncaught TypeError: Cannot read property '0' of undefined
    at value (app.min.js?v=1607625587:111)
    at ho (app.min.js?v=1607625587:78)
    at go (app.min.js?v=1607625587:78)
    at Mi (app.min.js?v=1607625587:78)
    at yc (app.min.js?v=1607625587:78)
    at us (app.min.js?v=1607625587:78)
    at cs (app.min.js?v=1607625587:78)
    at $c (app.min.js?v=1607625587:78)
    at app.min.js?v=1607625587:78
    at t.unstable_runWithPriority (app.min.js?v=1607625587:86)
    at Ha (app.min.js?v=1607625587:78)
    at Wa (app.min.js?v=1607625587:78)
    at Va (app.min.js?v=1607625587:78)
    at I (app.min.js?v=1607625587:78)
    at Qt (app.min.js?v=1607625587:78)
    at HTMLDocument.r (app.min.js?v=1607625587:111)
value @ app.min.js?v=1607625587:111
ho @ app.min.js?v=1607625587:78
go @ app.min.js?v=1607625587:78
Mi @ app.min.js?v=1607625587:78
yc @ app.min.js?v=1607625587:78
us @ app.min.js?v=1607625587:78
cs @ app.min.js?v=1607625587:78
$c @ app.min.js?v=1607625587:78
(anonymous) @ app.min.js?v=1607625587:78
t.unstable_runWithPriority @ app.min.js?v=1607625587:86
Ha @ app.min.js?v=1607625587:78
Wa @ app.min.js?v=1607625587:78
Va @ app.min.js?v=1607625587:78
I @ app.min.js?v=1607625587:78
Qt @ app.min.js?v=1607625587:78
r @ app.min.js?v=1607625587:111

**Comment by LiranSX** [comment]
Please reopen – still reproducible – see my last comment. It worked for something like a minute after upgrading to 3.55.2 + clearing all cache in chrome with no blank screen, and then started happening all over again for every click on the side menu

**Comment by jaedb** [comment]
Remember the ultimate check is running in incognito mode. I am dubious of the effectiveness of the reset features from within Iris.

**Comment by fmarzocca** [comment]
I can confirm that in Incognito mode, the application is much more reactive
and fast. Until now, the "black screen" bug didn't show yet.

**Comment by LiranSX** [comment]
still reproducible with incognito mode - right after the first screen "save" button:

app.min.js?v=1607625587:16 GET https://www.google-analytics.com/analytics.js net::ERR_NAME_NOT_RESOLVED
(anonymous) @ app.min.js?v=1607625587:16
W @ app.min.js?v=1607625587:16
i @ app.min.js?v=1607625587:111
vo @ app.min.js?v=1607625587:78
Mi @ app.min.js?v=1607625587:78
yc @ app.min.js?v=1607625587:78
us @ app.min.js?v=1607625587:78
cs @ app.min.js?v=1607625587:78
$c @ app.min.js?v=1607625587:78
(anonymous) @ app.min.js?v=1607625587:78
t.unstable_runWithPriority @ app.min.js?v=1607625587:86
Ha @ app.min.js?v=1607625587:78
Wa @ app.min.js?v=1607625587:78
Va @ app.min.js?v=1607625587:78
Kc @ app.min.js?v=1607625587:78
enqueueSetState @ app.min.js?v=1607625587:78
g.setState @ app.min.js?v=1607625587:70
(anonymous) @ app.min.js?v=1607625587:111
y @ app.min.js?v=1607625587:1
Cn @ app.min.js?v=1607625587:111
y @ app.min.js?v=1607625587:111
(anonymous) @ app.min.js?v=1607625587:111
Promise.then (async)
(anonymous) @ app.min.js?v=1607625587:111
Promise.then (async)
(anonymous) @ app.min.js?v=1607625587:111
(anonymous) @ app.min.js?v=1607625587:1
(anonymous) @ app.min.js?v=1607625587:111
(anonymous) @ app.min.js?v=1607625587:111
y @ app.min.js?v=1607625587:1
(anonymous) @ app.min.js?v=1607625587:111
(anonymous) @ app.min.js?v=1607625587:111
(anonymous) @ app.min.js?v=1607625587:111
(anonymous) @ app.min.js?v=1607625587:111
(anonymous) @ app.min.js?v=1607625587:111
(anonymous) @ app.min.js?v=1607625587:111
(anonymous) @ app.min.js?v=1607625587:111
(anonymous) @ app.min.js?v=1607625587:62
(anonymous) @ app.min.js?v=1607625587:111
(anonymous) @ app.min.js?v=1607625587:111
persist @ app.min.js?v=1607625587:111
(anonymous) @ app.min.js?v=1607625587:111
n @ app.min.js?v=1607625587:1
(anonymous) @ app.min.js?v=1607625587:62
n @ app.min.js?v=1607625587:1
(anonymous) @ app.min.js?v=1607625587:1
(anonymous) @ app.min.js?v=1607625587:1
app.min.js?v=1607625587:111 TypeError: Cannot read property '0' of undefined
    at value (app.min.js?v=1607625587:111)
    at ho (app.min.js?v=1607625587:78)
    at go (app.min.js?v=1607625587:78)
    at Mi (app.min.js?v=1607625587:78)
    at yc (app.min.js?v=1607625587:78)
    at us (app.min.js?v=1607625587:78)
    at cs (app.min.js?v=1607625587:78)
    at $c (app.min.js?v=1607625587:78)
    at app.min.js?v=1607625587:78
    at t.unstable_runWithPriority (app.min.js?v=1607625587:86)
    at Ha (app.min.js?v=1607625587:78)
    at Wa (app.min.js?v=1607625587:78)
    at Va (app.min.js?v=1607625587:78)
    at I (app.min.js?v=1607625587:78)
    at Qt (app.min.js?v=1607625587:78)
    at HTMLDocument.r (app.min.js?v=1607625587:111)
(anonymous) @ app.min.js?v=1607625587:111
ec @ app.min.js?v=1607625587:78
n.callback @ app.min.js?v=1607625587:78
fo @ app.min.js?v=1607625587:78
oc @ app.min.js?v=1607625587:78
ds @ app.min.js?v=1607625587:78
t.unstable_runWithPriority @ app.min.js?v=1607625587:86
Ha @ app.min.js?v=1607625587:78
ps @ app.min.js?v=1607625587:78
$c @ app.min.js?v=1607625587:78
(anonymous) @ app.min.js?v=1607625587:78
t.unstable_runWithPriority @ app.min.js?v=1607625587:86
Ha @ app.min.js?v=1607625587:78
Wa @ app.min.js?v=1607625587:78
Va @ app.min.js?v=1607625587:78
I @ app.min.js?v=1607625587:78
Qt @ app.min.js?v=1607625587:78
r @ app.min.js?v=1607625587:111
app.min.js?v=1607625587:111 Uncaught TypeError: Cannot read property '0' of undefined
    at value (app.min.js?v=1607625587:111)
    at ho (app.min.js?v=1607625587:78)
    at go (app.min.js?v=1607625587:78)
    at Mi (app.min.js?v=1607625587:78)
    at yc (app.min.js?v=1607625587:78)
    at us (app.min.js?v=1607625587:78)
    at cs (app.min.js?v=1607625587:78)
    at $c (app.min.js?v=1607625587:78)
    at app.min.js?v=1607625587:78
    at t.unstable_runWithPriority (app.min.js?v=1607625587:86)
    at Ha (app.min.js?v=1607625587:78)
    at Wa (app.min.js?v=1607625587:78)
    at Va (app.min.js?v=1607625587:78)
    at I (app.min.js?v=1607625587:78)
    at Qt (app.min.js?v=1607625587:78)
    at HTMLDocument.r (app.min.js?v=1607625587:111)
value @ app.min.js?v=1607625587:111
ho @ app.min.js?v=1607625587:78
go @ app.min.js?v=1607625587:78
Mi @ app.min.js?v=1607625587:78
yc @ app.min.js?v=1607625587:78
us @ app.min.js?v=1607625587:78
cs @ app.min.js?v=1607625587:78
$c @ app.min.js?v=1607625587:78
(anonymous) @ app.min.js?v=1607625587:78
t.unstable_runWithPriority @ app.min.js?v=1607625587:86
Ha @ app.min.js?v=1607625587:78
Wa @ app.min.js?v=1607625587:78
Va @ app.min.js?v=1607625587:78
I @ app.min.js?v=1607625587:78
Qt @ app.min.js?v=1607625587:78
r @ app.min.js?v=1607625587:111

**Comment by jaedb** [comment]
@LiranSX You are loading build number `1607625587` (see `app.min.js?v=1607625587` references), which is not the latest release. The latest release is [`1607625316`](https://github.com/jaedb/Iris/blob/master/mopidy_iris/static/index.html#L109). I am not sure of your setup, but for whatever reason you're not seeing the latest version which fixes this issue.

FYI you can see the build and version number either by using _View source_ of the webpage, or by looking at _Settings > Advanced > Version_.

It seems like your setup has quite heavy caching or some other issue involved. Many of the bugs you've helped debug seem to hang around even after performing upgrades. Are you restarting Mopidy after upgrading Iris?

**Comment by morithil** [comment]
@jaedb I have just done a fresh install of mopidy-iris with pip and it has installed build number 1607625587, that build no. is visible in incognito mode. As such I am still experiencing this bug.

**Comment by jaedb** [comment]
@morithil what version of Iris? And what exactly was your install process?

**Comment by morithil** [comment]
I just ran `sudo python3 -m pip install Mopidy-Iris` and it grabbed 3.55.2. Gui says it's 3.55.2 with build number 1607625587

**Comment by LiranSX** [comment]
James – please take a second look at the version – you are saying I'm using 1607625587 and that it is not the latest release, but the number 1607625587 is higher than  <https://github.com/jaedb/Iris/blob/master/mopidy_iris/static/index.html#L109> 1607625316

 

 <https://github.com/jaedb/Iris/blob/master/mopidy_iris/static/index.html#L109> 1607625316

1607625587

 

Liran

**Comment by jaedb** [comment]
This is a fair point. I'm more interested in why there is any discrepancy at all. Upon further investigation it looks like CircleCI didn't build the new code prior to releasing to PyPi, hence the latest release actually not including the latest code (which fixes this issue). 🤔 

I am running a local build and re-deployment with a new version `3.55.3` which should be on PyPi in the next 30 minutes. Can you please have a crack at upgrading and running `3.55.3`? Let me know how you get on and hopefully you (and anyone else affected) will be back in business.

**Comment by LiranSX** [comment]
tested it now - from first look it looks great man thx :) - didn't even need to delete cache/use incognito

**Comment by morithil** [comment]
Working great for me, excellent work!
